FROM lukemathwalker/cargo-chef:latest-rust-1-alpine3.21 AS chef
WORKDIR /app
RUN apk add --no-cache upx

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .

{% if protocol=='grpc' -%}
RUN apk add --no-cache protobuf-dev protoc
{% endif -%}

RUN cargo build --release
RUN upx --best --lzma /app/target/release/{{project_name}}

{% set runtime_base_image = "dhi.io/static:20251003-alpine3.23" if docker_hardened_images in features else "gcr.io/distroless/static-debian13" -%}
FROM {{ runtime_base_image }} AS runtime
COPY --from=builder /app/target/release/{{project_name}} /{{project_name}}

EXPOSE 8080

ENTRYPOINT ["/{{project_name}}"]