version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  jaeger:
    image: jaegertracing/jaeger
    ports:
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 9411:9411
    restart: unless-stopped
