[tools]
node = '24'
pnpm = "latest"

[tasks.dev]
description = "Build frontend"
run = '''
pnpm install --no-frozen-lockfile
pnpm run dev
'''

[tasks.build]
description = "Build frontend"
run = '''
pnpm install --no-frozen-lockfile
pnpm run test
pnpm run build
'''

[tasks.default]
description = "Default task: build frontend"
run = { task = "build" }