name: Build & Publish Helm Chart

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  publish-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      CHART_DIR: chart

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Log in to GHCR (Helm OCI)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Determine chart version
        id: version
        run: |
          # Detect if the triggering workflow was based on a tag (i.e., a release)
          REF="${{ github.event.workflow_run.head_branch }}"
          SHA="${GITHUB_SHA::7}"

          if [[ "$REF" == refs/tags/* ]]; then
            # Release build → use tag without SHA
            VERSION="${REF#refs/tags/}"
          else
            # Normal commit → append SHA
            BASE_VERSION=$(yq '.version' "$CHART_DIR/Chart.yaml")
            VERSION="${BASE_VERSION}-${SHA}"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Chart version: $VERSION"

      - name: Apply version to Chart.yaml
        run: |
          yq -i ".version = \"${{ steps.version.outputs.version }}\"" "$CHART_DIR/Chart.yaml"
          yq -i ".appVersion = \"${{ steps.version.outputs.version }}\"" "$CHART_DIR/Chart.yaml"

      - name: Build chart
        run: helm package "$CHART_DIR" --dependency-update

      - name: Push chart to GHCR (OCI)
        run: |
          FILE=$(ls *.tgz)
          helm push "$FILE" oci://ghcr.io/${{ github.repository_owner }}/helm-charts
